### ISSUE TITLE
Error when performing validations

### ISSUE THREAD

**Issue by postmodern** [carrierwaveuploader/carrierwave-datamapper#10]
Attempting to upload a file, but getting an exception after the validations are ran:

<pre>
carrierwave (0.5.8) lib/carrierwave/uploader/url.rb:18:in `expand_path'
carrierwave (0.5.8) lib/carrierwave/uploader/url.rb:18:in `to_s'
dm-validations (1.1.0) lib/dm-validations/validators/length_validator.rb:67:in `error_message_for'
dm-validations (1.1.0) lib/dm-validations/validators/length_validator.rb:48:in `call'
dm-validations (1.1.0) lib/dm-validations/contextual_validators.rb:104:in `execute'
dm-validations (1.1.0) lib/dm-validations/contextual_validators.rb:104:in `map'
dm-validations (1.1.0) lib/dm-validations/contextual_validators.rb:104:in `execute'
dm-validations (1.1.0) lib/dm-validations.rb:110:in `hookable__valid_ques_before_advised'
dm-core (1.1.0) lib/dm-core/support/hook.rb:303:in `valid?'
dm-core (1.1.0) lib/dm-core/support/hook.rb:301:in `catch'
dm-core (1.1.0) lib/dm-core/support/hook.rb:301:in `valid?'
dm-validations (1.1.0) lib/dm-validations.rb:81:in `save_self'
dm-core (1.1.0) lib/dm-core/resource.rb:1007:in `_save'
dm-core (1.1.0) lib/dm-core/resource.rb:1223:in `run_once'
dm-core (1.1.0) lib/dm-core/resource.rb:1006:in `_save'
dm-core (1.1.0) lib/dm-core/resource.rb:406:in `save'
dm-validations (1.1.0) lib/dm-validations.rb:69:in `save'
dm-validations (1.1.0) lib/dm-validations/support/context.rb:30:in `validation_context'
dm-validations (1.1.0) lib/dm-validations.rb:69:in `save'
</pre>

- Ruby: 1.8.7-p357
- Rails: 3.0.11
- DataMapper: 1.1.0
- carrierwave: 0.5.8
- carrierwave-datamapper: 0.2.0

**Comment by postmodern** [comment]
Nevermind, just needed to set the root directory for carrierwave. https://github.com/jnicklas/carrierwave/issues/415
