### ISSUE TITLE
to_xml and to_json broken

### ISSUE THREAD

**Issue by glortho** [carrierwaveuploader/carrierwave-datamapper#7]
When trying to render to xml or json a collection with dm-serializer, you get the following errors:

JSON

```
TypeError: wrong argument type nil (expected String)
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_json.rb:89:in `to_json'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_json.rb:89:in `to_json'
```

XML

```
RuntimeError: Illegal argument of type NilClass for Text constructor ()
    from /opt/local/lib/ruby/1.8/rexml/text.rb:83:in `initialize'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/xml/rexml.rb:22:in `new'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/xml/rexml.rb:22:in `add_node'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_xml.rb:44:in `to_xml_document'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_xml.rb:36:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_xml.rb:36:in `to_xml_document'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_xml.rb:112:in `to_xml_document'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-core-1.1.0/lib/dm-core/collection.rb:507:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-core-1.1.0/lib/dm-core/support/lazy_array.rb:411:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-core-1.1.0/lib/dm-core/collection.rb:504:in `each'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_xml.rb:111:in `to_xml_document'
    from /opt/local/lib/ruby/gems/1.8/gems/dm-serializer-1.1.0/lib/dm-serializer/to_xml.rb:94:in `to_xml'
```

Any ideas how to fix this?

**Comment by solnic** [comment]
@jedverity I'll look into this! Thanks for reporting the issue

**Comment by trevorturk** [comment]
This may be related to https://github.com/jnicklas/carrierwave/issues/337

**Comment by trevorturk** [comment]
@jedverity I think this may be fixed in the latest version. Can you please try and report back if not?
